/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.bined.operation.gui;

import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JButton;
import org.exbin.framework.utils.LanguageUtils;
import org.exbin.framework.utils.OkCancelListener;
import org.exbin.framework.utils.WindowUtils;
import org.exbin.framework.utils.UiUtils;
import org.exbin.framework.utils.handler.OkCancelService;

/**
 * Convert data control panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class ConvertDataControlPanel extends javax.swing.JPanel implements OkCancelService {

    private final java.util.ResourceBundle resourceBundle;
    private ConvertDataControlHandler handler;
    private OkCancelListener okCancelListener;

    public ConvertDataControlPanel() {
        this(LanguageUtils.getResourceBundleByClass(ConvertDataControlPanel.class));
        initComponents();
        init();
    }

    public ConvertDataControlPanel(java.util.ResourceBundle resourceBundle) {
        this.resourceBundle = resourceBundle;
        initComponents();
        init();
    }

    private void init() {
        okCancelListener = new OkCancelListener() {
            @Override
            public void okEvent() {
                performClick(ConvertDataControlHandler.ControlActionType.CONVERT);
            }

            @Override
            public void cancelEvent() {
                performClick(ConvertDataControlHandler.ControlActionType.CANCEL);
            }
        };
    }

    public void setHandler(ConvertDataControlHandler handler) {
        this.handler = handler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        convertToNewFileButton = new javax.swing.JButton();
        convertToClipboardButton = new javax.swing.JButton();
        convertButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        convertToNewFileButton.setText(resourceBundle.getString("convertToNewFileButton.text")); // NOI18N
        convertToNewFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertToNewFileButtonActionPerformed(evt);
            }
        });

        convertToClipboardButton.setText(resourceBundle.getString("convertToClipboardButton.text")); // NOI18N
        convertToClipboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertToClipboardButtonActionPerformed(evt);
            }
        });

        convertButton.setText(resourceBundle.getString("convertButton.text")); // NOI18N
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceBundle.getString("cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convertToNewFileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertToClipboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(convertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(convertButton)
                    .addComponent(convertToNewFileButton)
                    .addComponent(convertToClipboardButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        if (handler != null) {
            handler.controlActionPerformed(ConvertDataControlHandler.ControlActionType.CONVERT);
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (handler != null) {
            handler.controlActionPerformed(ConvertDataControlHandler.ControlActionType.CANCEL);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void convertToNewFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertToNewFileButtonActionPerformed
        if (handler != null) {
            handler.controlActionPerformed(ConvertDataControlHandler.ControlActionType.CONVERT_TO_NEW_FILE);
        }
    }//GEN-LAST:event_convertToNewFileButtonActionPerformed

    private void convertToClipboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertToClipboardButtonActionPerformed
        if (handler != null) {
            handler.controlActionPerformed(ConvertDataControlHandler.ControlActionType.CONVERT_TO_CLIPBOARD);
        }
    }//GEN-LAST:event_convertToClipboardButtonActionPerformed

    public void performClick(ConvertDataControlHandler.ControlActionType actionType) {
        switch (actionType) {
            case CONVERT: {
                UiUtils.doButtonClick(convertButton);
                break;
            }
            case CANCEL: {
                UiUtils.doButtonClick(cancelButton);
                break;
            }
            case CONVERT_TO_NEW_FILE: {
                UiUtils.doButtonClick(convertToNewFileButton);
                break;
            }
            case CONVERT_TO_CLIPBOARD: {
                UiUtils.doButtonClick(convertToClipboardButton);
                break;
            }
        }
    }

    @Nonnull
    @Override
    public JButton getDefaultButton() {
        return cancelButton;
    }

    @Nonnull
    @Override
    public OkCancelListener getOkCancelListener() {
        return okCancelListener;
    }

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        WindowUtils.invokeDialog(new ConvertDataControlPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton convertButton;
    private javax.swing.JButton convertToClipboardButton;
    private javax.swing.JButton convertToNewFileButton;
    // End of variables declaration//GEN-END:variables

}
