/*
 * Copyright (C) ExBin Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.exbin.framework.gui.menu.component;

import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicArrowButton;
import org.exbin.framework.gui.utils.WindowUtils;

/**
 * Drop down button panel.
 *
 * @version 0.2.1 2019/08/17
 * @author ExBin Project (http://exbin.org)
 */
@ParametersAreNonnullByDefault
public class DropDownButtonPanel extends javax.swing.JPanel {

    public DropDownButtonPanel() {
        initComponents();

        actionLabel.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                passMouseEventToParent(e);
            }

            @Override
            public void mousePressed(MouseEvent e) {
                passMouseEventToParent(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                passMouseEventToParent(e);
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                passMouseEventToParent(e);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                passMouseEventToParent(e);
            }

            private void passMouseEventToParent(MouseEvent me) {
                Component child = me.getComponent();
                Component parent = DropDownButtonPanel.this.getParent();

                //transform the mouse coordinate to be relative to the parent component:
                int deltaX = child.getX() + me.getX();
                int deltaY = child.getY() + me.getY();

                //dispatch it to the parent component
                parent.dispatchEvent(new MouseEvent(parent, me.getID(), me.getWhen(), me.getModifiers(), deltaX, deltaY, me.getClickCount(), false));
            }
        });
    }

    @Nonnull
    public JLabel getActionButton() {
        return actionLabel;
    }

    @Nonnull
    public JButton getMenuButton() {
        return menuButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButton = new BasicArrowButton(SwingConstants.SOUTH);
        actionLabel = new javax.swing.JLabel();

        setFocusable(false);
        setOpaque(false);

        menuButton.setBorderPainted(false);
        menuButton.setFocusable(false);
        menuButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menuButton.setMaximumSize(new java.awt.Dimension(15, 100));
        menuButton.setOpaque(false);

        actionLabel.setFocusable(false);
        actionLabel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(actionLabel)
                .addGap(0, 0, 0)
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WindowUtils.invokeDialog(new DropDownButtonPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JButton menuButton;
    // End of variables declaration//GEN-END:variables
}
